- test/gatling/README.md
- test/gatling/YLTWebInterfaceSimulation.scala
the scenario stress test accepts around 700 users.
> stress test scenario with gatlin

- front/src/css/rule.css
- front/src/less/rule.less
- front/src/views/rule.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/rulesChecker.js
- lib/tools/phantomas/custom_modules/modules/jQYLT/jQYLT.js
- test/core/customPoliciesTest.js
> Phantomas1.9

- lib/metadata/policies.js
Hi Loïc!
Thank you VERY much!
(I'm merging your change on the next branch going to production, instead of master. Next time I'll call it "develop" so it'll be more understandable.)
> Chore : Fix typo on policies

- bin/cli.js
- front/src/css/timeline.css
- front/src/js/app.js
- front/src/js/directives/jsChildrenDirective.js
- front/src/js/services/apiService.js
- front/src/less/timeline.less
- front/src/main.html
- front/src/views/timeline.html
- lib/server/controllers/apiController.js
- test/api/apiTest.js
Fixes #30.
Might need a better design but I'm not inspired at all...
> Show subqueries in timeline

- front/src/css/timeline.css
- front/src/js/controllers/timelineCtrl.js
- front/src/less/timeline.less
- front/src/views/timeline.html
> Scriptfilter

- front/src/css/timeline.css
- front/src/js/app.js
- front/src/js/controllers/timelineCtrl.js
- front/src/less/timeline.less
- front/src/main.html
- front/src/views/timeline.html
Scrolls to the right line in the profiler.
> Activate click on the timeline

- front/src/css/rule.css
- front/src/js/directives/offendersDirectives.js
- front/src/less/rule.less
- front/src/views/rule.html
- front/src/views/timeline.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/offendersHelpers.js
- lib/runner.js
- lib/server/controllers/apiController.js
- lib/tools/jsExecutionTransformer.js
- lib/tools/phantomas/custom_modules/core/scopeYLT/scopeYLT.js
- lib/tools/phantomas/custom_modules/modules/eventYLT/eventYLT.js
- lib/tools/phantomas/custom_modules/modules/jsTreeYLT/jsTreeYLT.js
- lib/tools/phantomas/custom_modules/modules/scrollListener/scrollListener.js
- test/core/offendersHelpersTest.js
- test/www/scroll-page.html
Adding two new rules: 
- Scroll events bound
- DOM access on scroll
> New experimental "Scroll bottlenecks" rules

- front/src/views/rule.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
Counting the number of HTML, JS and CSS files not being gzipped.
> New assetsNotGzipped rule

- front/src/css/main.css
- front/src/less/main.less
- front/src/views/dashboard.html
- front/src/views/screenshot.html
- lib/server/controllers/apiController.js
> Prevent fail when there's a screenshot error

- lib/runner.js
- lib/tools/weightChecker/weightChecker.js
- test/core/weightCheckerTest.js
- test/www/xml.xml
Fix #86. It was a bug with websites that load an XML file.
> Fix server freeze issue

- lib/metadata/policies.js
> fix typo: deboucing -> debouncing

- server_config/server_install.sh
- server_config/server_update.sh
Fixes deploy problem from #92.
> Exit server update script if npm install fails

- front/src/css/dashboard.css
- front/src/css/timeline.css
- front/src/js/controllers/dashboardCtrl.js
- front/src/less/dashboard.less
- front/src/less/timeline.less
- front/src/views/dashboard.html
> Change ng-click to real <a> on dashboard rows

- bin/cli.js
- package.json
> Add xml output option to the CLI

- front/src/css/index.css
- front/src/js/services/apiService.js
- front/src/less/index.less
- front/src/views/index.html
- lib/tools/weightChecker/weightChecker.js
- package.json
Adding basic HTTP authentication to the home screen "advanced options".
It's also available in the CLI and the NodeJS module.
> Basic auth

- front/src/js/controllers/ruleCtrl.js
- front/src/views/rule.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/runner.js
- lib/tools/colorDiff.js
- lib/tools/mediaQueriesChecker.js
- package.json
- test/core/mediaQueriesCheckerTest.js
Two new rules in the CSS Complexity category:
- Number of css breakpoints
- Number of non mobile-first media queries
Also contains a bug fix, for a rare bug:
"Cannot read property '1' of null error"
> Analyze media queries

- front/src/views/rule.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/runner.js
- lib/tools/isHttp2.js
- package.json
- test/core/isHttp2Test.js
This is a new rule that checks if the server is HTTP/2 compatible (or SPDY).
> Add Http2 detection

- lib/metadata/policies.js
jQuery 2.2 and 1.12 were just released. Updating the "jQuery version" rule.
> Release of jQuery 2.2

- lib/metadata/policies.js
- lib/tools/phantomas/custom_modules/modules/domHiddenYLT/domHiddenYLT.js
> Hidden pixels

- Vagrantfile
- server_config/server_install.sh
Allow a correct vagrant installation  
* Get official vagrant box
* Get correct node repository
* Add memory to box, node can't compile all dependencies with only 512M
> Vagrant install

- Vagrantfile
- server_config/server_install.sh
Remove some warning during vagrant deployment
* Remove some annoying warning
* Help to get only useful error message
Require #151 first
> Prevent Stdin warning

- .travis.yml
- package.json
> Update lwip dependency

- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/tools/weightChecker/imageOptimizer.js
Removing 2 CSS rules as advised by #155:
- Universal selectors
- Complex selectors by attribute
> Remove 2 rules related to CSS

- lib/metadata/scoreProfileGeneric.json
> Reduce the weight of the breakpoints count rule

- front/src/views/rule.html
- lib/metadata/policies.js
- lib/metadata/scoreProfileGeneric.json
- lib/tools/phantomas/custom_modules/core/scopeYLT/scopeYLT.js
- lib/tools/phantomas/custom_modules/modules/ajaxReqYLT/ajaxReqYLT.js
- lib/tools/phantomas/phantomasWrapper.js
- test/www/jquery-page.html
> Add a new rule for Synchronous XMLHttpRequest

- package.json
Fixes a few bugs in YLT:
- CSS parsing errors incorrectly handled
- mobile and tablet user-agents updated
- better caching duration calculation
> Update Phantomas to v1.16

- bin/server.js
- front/src/js/models/resultsFactory.js
- front/src/js/models/runsFactory.js
- front/src/main.html
- front/src/views/about.html
- front/src/views/dashboard.html
- front/src/views/queue.html
- front/src/views/resultSubHeader.html
- lib/server/controllers/frontController.js
- package.json
- server_config/settings-prod.json
- server_config/settings.json
- test/fixtures/settings.json
Hi @gmetais,
I did some changes to the application to add a support of subfolder use, for example behind a reverse proxy. The application was not usable in /subfolder because of the absolute paths used for assets and by AngularJS for views.
I added a "baseUrl" parameter in the settings file, by default set to "/". This parameter is injected in the <base> tag in the main HTML document. To be able to inject a parameter in the HTML, I added a HTML template engine named EJS. The static method from Express is still used for assets. Then I changed all the absolute paths for relative ones (assets, API, results, etc).
The scenario is to let "/" for a use on a domain without subfolder, and to configure the full URL for a subfolder (with a trailing slash). Example : …
> Adding subfolder support

- bin/cli.js
- front/src/js/services/apiService.js
- front/src/views/index.html
- lib/server/controllers/apiController.js
- lib/tools/phantomas/phantomasWrapper.js
- lib/tools/redownload/redownload.js
Allows you to set a HTTP proxy that will be used to access the tested webpage.
Fixes #78.
> Add proxy to the setting

- front/src/views/index.html
- package.json
This update includes support for multiple cookies (#195).
> Update Phantomas to 1.18

- Gruntfile.js
- package.json
- test/blanket.js
> Remove Blanket coverage testing

- front/src/main.html
> Don't load Google Analytics when not needed
